name: CI_CD-Workshop
on:
  push:
    branches:
    - master

jobs:
  slackNotification:
  name: Slack Notification
  run-on: ubuntu-latest
  steps: 
    - uses: actions/checkout@v4

    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
          SLACK_TITLE: "Image build and signed"
          SLACK_MESSAGE: |
            Name: Thiri Naing
            Matriculation: A0290837U
            Email: e1327868@u.nus.edu
            GitHub: https://github.com/Thiri-9/CI-CD-Workshop.git
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}