name: CI_CD-Workshop
on:
  push:
    branches:
    - v[0-9]+.[0-9]+

jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps: 
        - uses: actions/checkout@v3
        
        # Scan Vunerability
        - name: Run Trivy vulnerabilities scanner in fs mode
          uses: aquasecurity/trivy-action@master
          with:
              scan-type: 'fs'
              ignore-unfixed: true
              format: 'table'
              output: 'test.txt'
              severity: CRITICAL
              exit-code: 1

        # Slack Notification
        - name: Slack Notification
          uses: rtCamp/action-slack-notify@v2
          env:
              SLACK_TITLE: "Image build and signed"
              SLACK_MESSAGE: |
                Name: Thiri Naing
                Matriculation: A0290837U
                Email: e1327868@u.nus.edu
                GitHub: https://github.com/Thiri-9/CI-CD-Workshop.git
              SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
              SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK